version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - node
    volumes:
      - ./nginx-certs:/etc/nginx/certs

  node:
    build: .
    ports:
      - "8080"
      - "8088"
    volumes:
      - .:/app

  mongo:
    image: mongo
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - ./mongo-data:/data/db