version: '2'
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - node

  node:
    build: .
    ports:
      - "8080"
    volumes:
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - ./mongo-data:/data/db